function errorMsg = translateCameraError(errorCode)
%translateCameraError Converts the NDI camera error code into error message
%
% Syntax:
%   translateCameraError(error_code)
%       error_code is a string of the form ERRORXX, where XX is the two digit
%       number denoting the error code.  This function expects the complete
%       string.
%   
% Notes:
%   This function is derived from Polaris Application Program Interface Guide
%   rev 3
%
% See also:
%   ndi_camera/comm
% 

% 
% $Author: dmoses $
% $Revision: 1707 $
% $Date: 2009-04-24 11:35:08 -0400 (Fri, 24 Apr 2009) $ 
% Copyright: MAKO Surgical corp (2007)
% 

ndiErrorList = [...
{'ERROR01'},  {'Invalid command.'},...  
{'ERROR02'},  {'Command too long.'},...  
{'ERROR03'},  {'Command too short.'},...  
{'ERROR04'},  {'Command CRC error'},...  
{'ERROR05'},  {'Time-out on command execution.'},...  
{'ERROR06'},  {'Unable to set up new communication parameters.'},...  
{'ERROR07'},  {'Incorrect number of parameters.'},...  
{'ERROR08'},  {'Invalid port handle selected.'},...  
{'ERROR09'},  {'Invalid mode selected.'},...
{'ERROR0A'},  {'Invalid LED selected. The LED selected is out of range'},...  
{'ERROR0B'},  {'Invalid LED state selected. The LED state selected is out of range'},...  
{'ERROR0C'},  {'Command is invalid while in the current mode'},...  
{'ERROR0D'},  {'No tool is assigned to the selected port handle'},...  
{'ERROR0E'},  {'Selected port handle not initialized'},...  
{'ERROR0F'},  {'Selected port handle not enabled.'},...
{'ERROR10'},  {'System not initialized.'},...
{'ERROR11'},  {'Unable to stop tracking.'},...
{'ERROR12'},  {'Unable to start tracking.'},...
{'ERROR13'},  {'Polaris: Unable to initialize tool-in-port.'},... 
{'ERROR14'},  {'Invalid Position Sensor characterization parameters.'},...  
{'ERROR15'},  {'Unable to initialize the system.'},...
{'ERROR16'},  {'Unable to start Diagnostic mode.'},...
{'ERROR17'},  {'Unable to stop Diagnostic mode.'},...
{'ERROR18'},  {'Unable to check for environmental infrared light.'},...  
{'ERROR19'},  {'Unable to read devices firmware version information.'},...
{'ERROR1A'},  {'Internal system error. Unable to recover after, too much IR'},... 
{'ERROR1B'},  {'Unable to initialize for environmental infrared diagnostics.'},...  
{'ERROR1C'},  {'Unable to set marker activation signature.'},...  
{'ERROR1D'},  {'Unable to find SROM device IDs.'},...  
{'ERROR1E'},  {'Unable to read SROM device data.'},...
{'ERROR1F'},  {'Unable to write SROM device data.'},...
{'ERROR20'},  {'Unable to select SROM device for given port handle and SROM device ID.'},...  
{'ERROR21'},  {'Unable to test electrical current on tool.'},...  
{'ERROR22'},  {'Enabled tools are not supported by selected volume parameters.'},...
{'ERROR23'},  {'Command parameter is out of range.'},...  
{'ERROR24'},  {'Unable to select measurement volume.'},...
{'ERROR25'},  {'Unable to determine the system''s supported features list.'},...
{'ERROR28'},  {'Too many tools are enabled,'},...
{'ERROR29'},  {'Main processor firmware is corrupt.'},...  
{'ERROR2A'},  {'No memory is available for dynamic allocation (heap is full)'},...  
{'ERROR2B'},  {'The requested port handle has not been allocated.'},...  
{'ERROR2C'},  {'The requested port handle has become unoccupied.'},...  
{'ERROR2D'},  {'All handles have been allocated.'},...  
{'ERROR2E'},  {'Incompatible firmware versions.'},...
{'ERROR2F'},  {'Invalid port description.'},...  
{'ERROR30'},  {'Requested port is already assigned a port handle.'},...  
{'ERROR31'},  {'Invalid input or output state.'},...  
{'ERROR32'},  {'Invalid operation for the device associated with the specified port handle.'},...  
{'ERROR33'},  {'Feature not available.'},...  
{'ERROR34'},  {'User parameter does not exist.'},...  
{'ERROR35'},  {'Invalid value type (e.g. string instead of integer).'},...  
{'ERROR36'},  {'User parameter value set is out of valid range.'},...  
{'ERROR37'},  {'User parameter array index is out of valid range.'},...  
{'ERROR38'},  {'User parameter size is incorrect.'},...  
{'ERROR39'},  {'Permission denied. file or user parameter is read-only.'},...  
{'ERROR3B'},  {'ERRORFile not found.'},...  
{'ERROR3C'},  {'Error writing to file.'},...  
{'ERROR40'},  {'Tool definition file error.'},...
{'ERROR41'},  {'Tool characteristics not supported.'},...
{'ERROR42'},  {'Device not present.'},...
{'ERRORA2'},  {'General purpose input/output access on synchronization port failed.'},...  
{'ERRORF1'},  {'Too much environmental infrared light.'},...  
{'ERRORF4'},  {'Unable to erase Flash SROM device'},...  
{'ERRORF5'},  {'Unable to write Flash SROM device'},...  
{'ERRORF6'},  {'Unable to read Flash SROM device'},...  
];

errorIndex = strmatch(errorCode,ndiErrorList)+1;

if (~isempty(errorIndex))
    errorMsg = sprintf('%s: %s',errorCode,cell2mat(ndiErrorList(errorIndex)));
else
    errorMsg = sprintf('%s: Unidentified or Reserved error code',errorCode);
end



%---- END OF FILE -----