function response = disconnect(mscribe_obj)
%DISCONNECT releases handles used by the micro scribe.

%
% $Author: dberman $
% $Revision: 3674 $
% $Date: 2014-12-15 16:41:28 -0500 (Mon, 15 Dec 2014) $
% Copyright: MAKO Surgical corp (2008)
%

%%
dllname = 'armdll64';
try
    % ArmEnd must be called to close the session. 
    % Failure to do so will leave the thread and its owning process running until the computer is restarted.  
    calllib(dllname,'ArmEnd')
    pause(.2)
catch
end


try
    calllib(dllname,'ArmDisconnect')
catch
end

try
    % We have verified that there is an error in the documentation for
    % LIBSTRUCT. To unload a library, all structures generated by LIBSTRUCT must be cleared from the MATLAB workspace.
    % To work around this issue, clear any LIBSTRUCT objects related to a library before calling UNLOADLIBRARY.
    clear mscribe_obj;
    
    pause(.2)
catch
    response = -1; % failed
end

try
    %Unloading the library
    unloadlibrary(dllname)
catch
end

response = 0; % succeeded

disp('MicroScribe Disconnected!')
% ----- END OF FILE -------