function errorMsg = translateErrorCode(errorCode)
% The function translates GALIL error code to the corresponding message.

% Note: The error list is contained in the GALIL Windows API documentation
% 'dmcwin32_windowsAPI.pdf'. Please refer to this document for more
% details.

% 
% $Author: dmoses $
% $Revision: 1707 $
% $Date: 2009-04-24 11:35:08 -0400 (Fri, 24 Apr 2009) $ 
% Copyright: MAKO Surgical corp (2007)
% 

GALILErrorList = [...
    {'-1'}, {'DMCERROR_TIMEOUT: A time-out occurred while waiting for a response from the Galil controller'},...
    {'-2'}, {'DMCERROR_COMMAND: There was an error with the command sent to the Galil controller'},...
    {'-3'}, {'DMCERROR_CONTROLLER: The Galil controller could not be found in Windows registry'},...
    {'-4'}, {'DMCERROR_FILE: File could not be opened. This error usually occurs when the file name is invalid or the file can not be found'},...
    {'-5'}, {'DMCERROR_DRIVER: Device driver could not be opened, or a read or write error occurred'},...
    {'-6'}, {'DMCERROR_HANDLE: Invalid Galil controller handle. This error will occur if you try to communicate with the Galil controller without first calling DMCOpen'},...
    {'-7'}, {'DMCERROR_HMODULE: Support dynamic link library could not be loaded'},...
    {'-8'}, {'DMCERROR_MEMORY: GALIL Out of memory. SORRY!!!'},...
    {'-9'}, {'DMCERROR_BUFFERFULL: Response from the controller was larger than the response buffer supplied'},...
    {'-10'}, {'DMCERROR_RESPONSEDATA: Response from the controller overflowed the internal additional response buffer'},...  
    {'-11'}, {'DMCERROR_DMA: Could not communicate with DMA channel. '},...
    {'-12'}, {'DMCERROR_ARGUMENT: One or more required arguments to a DMC API function call was NULL'},...
    {'-13'}, {'DMCERROR_DATARECORD: Could not access data record'},...
    {'-14'}, {'DMCERROR_DOWNLOAD: File download failed. The problem is most likely a file that has too many lines or one or more lines which exceed the line length restriction'},...
    {'-15'}, {'DMCERROR_FIRMWARE: Could not update the controller firmware'},...
    {'-16'}, {'DMCERROR_CONVERSION: Could not convert the DMC command (ASCII to binary or binary to ASCII)'},...
    {'-17'}, {'DMCERROR_RESOURCE: Could not access or modify the controller registry information'},...
    {'-18'}, {'DMCERROR_REGISTRY: Windows reports a resource conflict with the current hardware configuration'},...
    {'-19'}, {'DMCERROR_BUSY: Could not write to the controller because it is currently busy'},...
    {'-20'}, {'DMCERROR_DEVICE_DISCONNECTED: A Windows plug-and-play controller, such as one which communicates through USB, was disconnected from the system'},...
    {'-21'}, {'DMCERROR_TIMEING_ERROR: Data is not being transferred to controller fast enough to maintain time synchronization'},...
    {'-22'}, {'DMCERROR_WRITEBUFFER_TOO_LARGE: The user supplied buffer is too large. Must be < 1024 bytes.'},...
    {'-23'}, {'DMCERROR_NO_MODIFY_PNP_CONTROLLER: Registry modification of PnP controllers is not allowed'},...
    {'-24'}, {'DMCERROR_FUNCTION_OBSOLETE: This function is obsolete'},...
    {'-25'}, {'DMCERROR_STREAMING_COMMAND_IN_PROGRESS: A different process is using a streaming command(LS,UL,ED,QD,QU)'},...
    {'-26'}, {'DMCERROR_DEVICEDRIVER_VERSION_TOO_OLD: The device driver needed to communicate with the selected controller is too old for this communication dll.'},...
    {'-27'}, {'DMCERROR_STREAMING_COMMAND_MUST_BE_SOLITARY: Streaming commands (LS, UL, ED, QD, QU) cannot be mixed with other commands on the command line.'},...
];

errorIndex = strmatch(errorCode,GALILErrorList)+1;

if (~isempty(errorIndex))
    errorMsg = sprintf('%s: %s',errorCode,cell2mat(GALILErrorList(errorIndex)));
else
    errorMsg = sprintf('%s: Unidentified or Reserved error code',errorCode);
end
